name: golangci-lint
on:
  push:
    paths-ignore:
      - "*.md"
  pull_request:
    paths-ignore:
    - "*.md"
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: --enable=prealloc,misspell,goconst,bodyclose,unconvert --out-format=colored-line-number --sort-results --max-issues-per-linter=0 --max-same-issues=0
