name: Docker build

on:
  push:
    paths-ignore:
      - "*.md"
  pull_request:
    paths-ignore:
    - "*.md"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build --tag memoiredb:buildcheck .