name: Go Unit testing & Building

on: [ push, pull_request ]

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Execute unit tests
      run: go test -v ./...

    - name: Build application
      run: go build -v .
